# -*- coding: utf-8 -*-
"""1 Consumo de API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNhtfhtzvNM8ZvOmj1QXWKTKJk7LOoqq
"""

import requests

url = 'https://viacep.com.br/ws/'
cep = '30140071'
formato = '/xml/'

r = requests.get(url + cep + formato)
if r.status_code == 200:
    print("\nXML :\n", r.text, "\n")
else:
    print("Não houve sucesso na requisição. Código:", r.status_code)

import requests

url = 'https://viacep.com.br/ws/'
cep_inicial = 30140071
formato = '/json/'

for i in range(5):
    cep = str(cep_inicial + i)
    r = requests.get(url + cep + formato)
    if r.status_code == 200:
        print(f"\nCEP {cep} : {r.json()}\n")
    else:
        print(f"Erro ao consultar o CEP {cep}: {r.status_code}")

import requests
from urllib.parse import quote

base = 'https://viacep.com.br/ws'
uf = 'MG'
cidade = 'Belo Horizonte'
rua = 'Rua dos Aimores'
path = f'/{quote(uf)}/{quote(cidade)}/{quote(rua)}/json/'
r = requests.get(base + path)
if r.status_code == 200:
    registros = r.json()
    print(f"Encontrados {len(registros)} registros\n")
    for rec in registros:
        print(rec)
else:
    print("Erro na requisição:", r.status_code)

import requests

url = 'https://viacep.com.br/abc/'
r = requests.get(url)
print("Código de retorno:", r.status_code)
print("Texto da resposta:\n", r.text)

import requests

r = requests.get('http://www.google.com/search', params={'q': 'elson de abreu'})
if r.status_code == 200:
    with open("/content/resultado_google.html", "w", encoding="utf-8") as f:
        f.write(r.text)
    print("Resultado salvo em '/content/resultado_google.html'")
else:
    print("Não houve sucesso na requisição. Código:", r.status_code)